BITPAY_API_KEY = ENV['BITPAY_API_KEY'].nil? ? 'blah' : ENV['BITPAY_API_KEY']
BITPAY_HOST = 'localhost:3030'
BITPAY_CONNECT_URL = ENV['BITPAY_URL'].nil? ? "http://#{BITPAY_HOST}" : ENV['BITPAY_URL']
DEFAULT_TRANSACTION_SPEED = 'low'
DEFAULT_FULL_NOTIFICATION = 'true'

EXPIRED_STATUS_RESPONSE_AMT = 1111.11
INVALID_STATUS_RESPONSE_AMT = 9999.99
  
MINIMUM_BTC_PRICE = 0.1
