Stripe.api_key = ENV['STRIPE_SECRET'].nil? ? 'sk_0INin2jwTLiOY4xFw8wLZO3DWQWul' : ENV['STRIPE_SECRET']
STRIPE_PUBLIC_KEY = ENV['STRIPE_PUBLIC'].nil? ? 'pk_0INiaGmtnANOHmlgZKUD44MQ8Na41' : ENV['STRIPE_PUBLIC_LIVE']
