# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: machovy_development
  username: rails
  password: rails
  encoding: utf8
  pool: 5

test: &test
  adapter: postgresql
  database: machovy_test
  username: rails
  password: rails
  encoding: utf8
  pool: 5
